version: '3.8'

services:
  # Service for the text-to-cad backend (Python/API)
  backend:
    build:
      context: ./text-to-cad/backend
    env_file: ./.env
    volumes:
      - backend_temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service for the text-to-cad frontend
  frontend:
    build:
      context: ./text-to-cad/frontend
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  # Service for your personal website
  portfolio:
    build:
      context: ./saloni-balkondekar-website
    restart: unless-stopped

  # The Nginx reverse proxy
  proxy:
    build:
      context: ./nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - portfolio
    restart: unless-stopped

volumes:
  backend_temp:
    driver: local